// <auto-generated />
using System;
using ASP.NET_Web_App_Core__MVC_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_Web_App_Core__MVC_.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208145959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Agent", b =>
                {
                    b.Property<int>("AgentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AgentID");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentID = 1,
                            Address = "123 Main St, New York, NY 10001",
                            AgentName = "TechWorld Solutions",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@techworld.com",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            AgentID = 2,
                            Address = "456 Oak Ave, Los Angeles, CA 90001",
                            AgentName = "Global Electronics",
                            CreatedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@globalelec.com",
                            PhoneNumber = "555-0102"
                        },
                        new
                        {
                            AgentID = 3,
                            Address = "789 Pine Rd, Chicago, IL 60601",
                            AgentName = "Digital Hub Inc",
                            CreatedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sales@digitalhub.com",
                            PhoneNumber = "555-0103"
                        },
                        new
                        {
                            AgentID = 4,
                            Address = "321 Elm St, Houston, TX 77001",
                            AgentName = "Smart Devices Co",
                            CreatedDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orders@smartdevices.com",
                            PhoneNumber = "555-0104"
                        },
                        new
                        {
                            AgentID = 5,
                            Address = "654 Maple Dr, Phoenix, AZ 85001",
                            AgentName = "Prime Technology",
                            CreatedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "support@primetech.com",
                            PhoneNumber = "555-0105"
                        },
                        new
                        {
                            AgentID = 6,
                            Address = "987 Cedar Ln, Philadelphia, PA 19101",
                            AgentName = "Metro Electronics",
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@metroelec.com",
                            PhoneNumber = "555-0106"
                        },
                        new
                        {
                            AgentID = 7,
                            Address = "147 Birch Blvd, San Antonio, TX 78201",
                            AgentName = "Tech Express",
                            CreatedDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@techexpress.com",
                            PhoneNumber = "555-0107"
                        },
                        new
                        {
                            AgentID = 8,
                            Address = "258 Spruce Way, San Diego, CA 92101",
                            AgentName = "Innovation Store",
                            CreatedDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sales@innovstore.com",
                            PhoneNumber = "555-0108"
                        },
                        new
                        {
                            AgentID = 9,
                            Address = "369 Willow Ct, Dallas, TX 75201",
                            AgentName = "Future Electronics",
                            CreatedDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orders@futureelec.com",
                            PhoneNumber = "555-0109"
                        },
                        new
                        {
                            AgentID = 10,
                            Address = "741 Ash Ave, San Jose, CA 95101",
                            AgentName = "Elite Tech Group",
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@elitetech.com",
                            PhoneNumber = "555-0110"
                        },
                        new
                        {
                            AgentID = 11,
                            Address = "852 Poplar St, Austin, TX 78701",
                            AgentName = "NextGen Supplies",
                            CreatedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@nextgensup.com",
                            PhoneNumber = "555-0111"
                        },
                        new
                        {
                            AgentID = 12,
                            Address = "963 Walnut Rd, Jacksonville, FL 32099",
                            AgentName = "Quantum Electronics",
                            CreatedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sales@quantumelec.com",
                            PhoneNumber = "555-0112"
                        },
                        new
                        {
                            AgentID = 13,
                            Address = "159 Cherry Ln, Fort Worth, TX 76101",
                            AgentName = "Apex Technology",
                            CreatedDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orders@apextech.com",
                            PhoneNumber = "555-0113"
                        },
                        new
                        {
                            AgentID = 14,
                            Address = "357 Hickory Dr, Columbus, OH 43085",
                            AgentName = "Vision Tech Co",
                            CreatedDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@visiontech.com",
                            PhoneNumber = "555-0114"
                        },
                        new
                        {
                            AgentID = 15,
                            Address = "486 Chestnut Way, Charlotte, NC 28201",
                            AgentName = "Summit Electronics",
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@summitelec.com",
                            PhoneNumber = "555-0115"
                        });
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-performance ultrabook",
                            ItemName = "Laptop Dell XPS 13",
                            Price = 1299.99m,
                            Size = "13 inch",
                            StockQuantity = 50
                        },
                        new
                        {
                            ItemID = 2,
                            CreatedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest Apple smartphone",
                            ItemName = "iPhone 15 Pro",
                            Price = 999.99m,
                            Size = "Medium",
                            StockQuantity = 100
                        },
                        new
                        {
                            ItemID = 3,
                            CreatedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Android flagship phone",
                            ItemName = "Samsung Galaxy S24",
                            Price = 899.99m,
                            Size = "Large",
                            StockQuantity = 80
                        },
                        new
                        {
                            ItemID = 4,
                            CreatedDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional tablet",
                            ItemName = "iPad Pro 12.9",
                            Price = 1099.99m,
                            Size = "Large",
                            StockQuantity = 60
                        },
                        new
                        {
                            ItemID = 5,
                            CreatedDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight laptop",
                            ItemName = "MacBook Air M2",
                            Price = 1199.99m,
                            Size = "13 inch",
                            StockQuantity = 45
                        },
                        new
                        {
                            ItemID = 6,
                            CreatedDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise-cancelling headphones",
                            ItemName = "Sony WH-1000XM5",
                            Price = 399.99m,
                            Size = "Small",
                            StockQuantity = 120
                        },
                        new
                        {
                            ItemID = 7,
                            CreatedDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smartwatch",
                            ItemName = "Apple Watch Series 9",
                            Price = 429.99m,
                            Size = "Small",
                            StockQuantity = 90
                        },
                        new
                        {
                            ItemID = 8,
                            CreatedDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4K professional monitor",
                            ItemName = "Dell UltraSharp Monitor",
                            Price = 549.99m,
                            Size = "27 inch",
                            StockQuantity = 70
                        },
                        new
                        {
                            ItemID = 9,
                            CreatedDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless mouse",
                            ItemName = "Logitech MX Master 3",
                            Price = 99.99m,
                            Size = "Small",
                            StockQuantity = 150
                        },
                        new
                        {
                            ItemID = 10,
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming keyboard",
                            ItemName = "Mechanical Keyboard RGB",
                            Price = 149.99m,
                            Size = "Medium",
                            StockQuantity = 110
                        },
                        new
                        {
                            ItemID = 11,
                            CreatedDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "NVMe solid state drive",
                            ItemName = "Samsung SSD 1TB",
                            Price = 129.99m,
                            Size = "Small",
                            StockQuantity = 200
                        },
                        new
                        {
                            ItemID = 12,
                            CreatedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mirrorless camera",
                            ItemName = "Canon EOS R6",
                            Price = 2499.99m,
                            Size = "Large",
                            StockQuantity = 30
                        },
                        new
                        {
                            ItemID = 13,
                            CreatedDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming console",
                            ItemName = "Nintendo Switch OLED",
                            Price = 349.99m,
                            Size = "Medium",
                            StockQuantity = 85
                        },
                        new
                        {
                            ItemID = 14,
                            CreatedDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Next-gen console",
                            ItemName = "PlayStation 5",
                            Price = 499.99m,
                            Size = "Large",
                            StockQuantity = 40
                        },
                        new
                        {
                            ItemID = 15,
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming console",
                            ItemName = "Xbox Series X",
                            Price = 499.99m,
                            Size = "Large",
                            StockQuantity = 55
                        },
                        new
                        {
                            ItemID = 16,
                            CreatedDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless earbuds",
                            ItemName = "AirPods Pro 2",
                            Price = 249.99m,
                            Size = "Small",
                            StockQuantity = 130
                        },
                        new
                        {
                            ItemID = 17,
                            CreatedDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "E-reader",
                            ItemName = "Kindle Paperwhite",
                            Price = 139.99m,
                            Size = "Small",
                            StockQuantity = 95
                        },
                        new
                        {
                            ItemID = 18,
                            CreatedDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Action camera",
                            ItemName = "GoPro Hero 12",
                            Price = 399.99m,
                            Size = "Small",
                            StockQuantity = 75
                        },
                        new
                        {
                            ItemID = 19,
                            CreatedDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cordless vacuum cleaner",
                            ItemName = "Dyson V15 Vacuum",
                            Price = 649.99m,
                            Size = "Large",
                            StockQuantity = 50
                        },
                        new
                        {
                            ItemID = 20,
                            CreatedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smart doorbell",
                            ItemName = "Ring Video Doorbell",
                            Price = 99.99m,
                            Size = "Small",
                            StockQuantity = 140
                        });
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("AgentID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("AgentID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            AgentID = 1,
                            Notes = "Bulk order",
                            OrderDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 2599.98m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 2,
                            AgentID = 2,
                            Notes = "Priority delivery",
                            OrderDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            TotalAmount = 999.99m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 3,
                            AgentID = 3,
                            Notes = "Regular order",
                            OrderDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 1799.97m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 4,
                            AgentID = 4,
                            Notes = "Express shipping",
                            OrderDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Processing",
                            TotalAmount = 549.99m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 5,
                            AgentID = 5,
                            Notes = "Large order",
                            OrderDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 3299.97m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 6,
                            AgentID = 1,
                            Notes = "Standard shipping",
                            OrderDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            TotalAmount = 1529.97m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 7,
                            AgentID = 6,
                            Notes = "Gift wrap requested",
                            OrderDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 829.98m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 8,
                            AgentID = 7,
                            Notes = "Corporate order",
                            OrderDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            TotalAmount = 2049.97m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 9,
                            AgentID = 8,
                            Notes = "Regular customer",
                            OrderDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 499.99m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 10,
                            AgentID = 9,
                            Notes = "Urgent order",
                            OrderDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Processing",
                            TotalAmount = 1449.97m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 11,
                            AgentID = 10,
                            Notes = "Wholesale",
                            OrderDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 999.96m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 12,
                            AgentID = 2,
                            Notes = "Standard order",
                            OrderDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            TotalAmount = 679.98m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 13,
                            AgentID = 11,
                            Notes = "Bulk discount",
                            OrderDate = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 1899.96m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 14,
                            AgentID = 12,
                            Notes = "Valentine special",
                            OrderDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            TotalAmount = 349.99m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 15,
                            AgentID = 13,
                            Notes = "Premium items",
                            OrderDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 2599.95m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 16,
                            AgentID = 3,
                            Notes = "Fast delivery",
                            OrderDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Processing",
                            TotalAmount = 799.98m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 17,
                            AgentID = 14,
                            Notes = "Regular order",
                            OrderDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 1299.98m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 18,
                            AgentID = 15,
                            Notes = "Standard shipping",
                            OrderDate = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            TotalAmount = 549.98m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 19,
                            AgentID = 4,
                            Notes = "Corporate purchase",
                            OrderDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 1949.96m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 20,
                            AgentID = 5,
                            Notes = "Gift order",
                            OrderDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending",
                            TotalAmount = 429.99m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 21,
                            AgentID = 6,
                            Notes = "High value order",
                            OrderDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 3199.96m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 22,
                            AgentID = 7,
                            Notes = "Express delivery",
                            OrderDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Processing",
                            TotalAmount = 899.97m,
                            UserID = 3
                        },
                        new
                        {
                            OrderID = 23,
                            AgentID = 8,
                            Notes = "Bulk order",
                            OrderDate = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 1599.97m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 24,
                            AgentID = 9,
                            Notes = "Regular shipping",
                            OrderDate = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped",
                            TotalAmount = 749.98m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 25,
                            AgentID = 10,
                            Notes = "Premium order",
                            OrderDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed",
                            TotalAmount = 2249.96m,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ItemID = 1,
                            OrderID = 1,
                            Quantity = 2,
                            UnitAmount = 1299.99m
                        },
                        new
                        {
                            ID = 2,
                            ItemID = 2,
                            OrderID = 2,
                            Quantity = 1,
                            UnitAmount = 999.99m
                        },
                        new
                        {
                            ID = 3,
                            ItemID = 3,
                            OrderID = 3,
                            Quantity = 2,
                            UnitAmount = 899.99m
                        },
                        new
                        {
                            ID = 4,
                            ItemID = 8,
                            OrderID = 4,
                            Quantity = 1,
                            UnitAmount = 549.99m
                        },
                        new
                        {
                            ID = 5,
                            ItemID = 1,
                            OrderID = 5,
                            Quantity = 1,
                            UnitAmount = 1299.99m
                        },
                        new
                        {
                            ID = 6,
                            ItemID = 4,
                            OrderID = 5,
                            Quantity = 1,
                            UnitAmount = 1099.99m
                        },
                        new
                        {
                            ID = 7,
                            ItemID = 3,
                            OrderID = 5,
                            Quantity = 1,
                            UnitAmount = 899.99m
                        },
                        new
                        {
                            ID = 8,
                            ItemID = 6,
                            OrderID = 6,
                            Quantity = 2,
                            UnitAmount = 399.99m
                        },
                        new
                        {
                            ID = 9,
                            ItemID = 16,
                            OrderID = 6,
                            Quantity = 3,
                            UnitAmount = 249.99m
                        },
                        new
                        {
                            ID = 10,
                            ItemID = 7,
                            OrderID = 7,
                            Quantity = 1,
                            UnitAmount = 429.99m
                        },
                        new
                        {
                            ID = 11,
                            ItemID = 6,
                            OrderID = 7,
                            Quantity = 1,
                            UnitAmount = 399.99m
                        },
                        new
                        {
                            ID = 12,
                            ItemID = 12,
                            OrderID = 8,
                            Quantity = 1,
                            UnitAmount = 2499.99m
                        },
                        new
                        {
                            ID = 13,
                            ItemID = 14,
                            OrderID = 9,
                            Quantity = 1,
                            UnitAmount = 499.99m
                        },
                        new
                        {
                            ID = 14,
                            ItemID = 10,
                            OrderID = 10,
                            Quantity = 3,
                            UnitAmount = 149.99m
                        },
                        new
                        {
                            ID = 15,
                            ItemID = 9,
                            OrderID = 10,
                            Quantity = 10,
                            UnitAmount = 99.99m
                        },
                        new
                        {
                            ID = 16,
                            ItemID = 16,
                            OrderID = 11,
                            Quantity = 4,
                            UnitAmount = 249.99m
                        },
                        new
                        {
                            ID = 17,
                            ItemID = 11,
                            OrderID = 12,
                            Quantity = 2,
                            UnitAmount = 129.99m
                        },
                        new
                        {
                            ID = 18,
                            ItemID = 7,
                            OrderID = 12,
                            Quantity = 1,
                            UnitAmount = 429.99m
                        },
                        new
                        {
                            ID = 19,
                            ItemID = 2,
                            OrderID = 13,
                            Quantity = 2,
                            UnitAmount = 999.99m
                        },
                        new
                        {
                            ID = 20,
                            ItemID = 13,
                            OrderID = 14,
                            Quantity = 1,
                            UnitAmount = 349.99m
                        },
                        new
                        {
                            ID = 21,
                            ItemID = 15,
                            OrderID = 15,
                            Quantity = 5,
                            UnitAmount = 499.99m
                        },
                        new
                        {
                            ID = 22,
                            ItemID = 6,
                            OrderID = 16,
                            Quantity = 2,
                            UnitAmount = 399.99m
                        },
                        new
                        {
                            ID = 23,
                            ItemID = 1,
                            OrderID = 17,
                            Quantity = 1,
                            UnitAmount = 1299.99m
                        },
                        new
                        {
                            ID = 24,
                            ItemID = 19,
                            OrderID = 18,
                            Quantity = 1,
                            UnitAmount = 649.99m
                        },
                        new
                        {
                            ID = 25,
                            ItemID = 18,
                            OrderID = 19,
                            Quantity = 2,
                            UnitAmount = 399.99m
                        },
                        new
                        {
                            ID = 26,
                            ItemID = 5,
                            OrderID = 19,
                            Quantity = 1,
                            UnitAmount = 1199.99m
                        },
                        new
                        {
                            ID = 27,
                            ItemID = 7,
                            OrderID = 20,
                            Quantity = 1,
                            UnitAmount = 429.99m
                        },
                        new
                        {
                            ID = 28,
                            ItemID = 14,
                            OrderID = 21,
                            Quantity = 4,
                            UnitAmount = 499.99m
                        },
                        new
                        {
                            ID = 29,
                            ItemID = 15,
                            OrderID = 21,
                            Quantity = 2,
                            UnitAmount = 499.99m
                        },
                        new
                        {
                            ID = 30,
                            ItemID = 3,
                            OrderID = 22,
                            Quantity = 1,
                            UnitAmount = 899.99m
                        },
                        new
                        {
                            ID = 31,
                            ItemID = 8,
                            OrderID = 23,
                            Quantity = 2,
                            UnitAmount = 549.99m
                        },
                        new
                        {
                            ID = 32,
                            ItemID = 15,
                            OrderID = 23,
                            Quantity = 1,
                            UnitAmount = 499.99m
                        },
                        new
                        {
                            ID = 33,
                            ItemID = 20,
                            OrderID = 24,
                            Quantity = 5,
                            UnitAmount = 99.99m
                        },
                        new
                        {
                            ID = 34,
                            ItemID = 16,
                            OrderID = 24,
                            Quantity = 1,
                            UnitAmount = 249.99m
                        },
                        new
                        {
                            ID = 35,
                            ItemID = 4,
                            OrderID = 25,
                            Quantity = 2,
                            UnitAmount = 1099.99m
                        });
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            IsLocked = false,
                            Password = "admin123",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            IsLocked = false,
                            Password = "user123",
                            Role = "User",
                            UserName = "john_doe"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@example.com",
                            IsLocked = false,
                            Password = "user123",
                            Role = "User",
                            UserName = "jane_smith"
                        });
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Order", b =>
                {
                    b.HasOne("ASP.NET_Web_App_Core__MVC_.Models.Agent", "Agent")
                        .WithMany("Orders")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASP.NET_Web_App_Core__MVC_.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.OrderDetail", b =>
                {
                    b.HasOne("ASP.NET_Web_App_Core__MVC_.Models.Item", "Item")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASP.NET_Web_App_Core__MVC_.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Agent", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Item", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASP.NET_Web_App_Core__MVC_.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
